version: "3.8"

services:
  web:
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - HOST=0.0.0.0
      - PORT=3000
    restart: unless-stopped
    # Configure healthcheck
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Set resource limits
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 512M
    # Build configuration
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development

networks:
  app-network:
    driver: bridge
